services:
  server:
    environment:
      - UPSTASH_REDIS_TOKEN=${UPSTASH_REDIS_TOKEN}
      - UPSTASH_REDIS_URL=${UPSTASH_REDIS_URL}
    build:
      context: .
      target: final
    ports:
      - 8080:8080
