services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - 8080:8080
    volumes:
      # - ./:/app
      - type: bind
        source: .
        target: /app
