openapi: 3.0.3
info:
  title: Scene Hunter API
  description: Scene HunterのAPI定義書
  version: 0.1.0
servers:
  - url: http://localhost:8080/api
    description: ローカル開発環境
  - url: https://sh.yashikota.com/api
    description: 本番環境
tags:
  - name: id
    description: ユーザーIDに関するAPI
  - name: room
    description: 部屋に関するAPI
  - name: debug
    description: デバッグ用API
paths:
  /generate_user_id:
    get:
      tags:
        - id
      summary: ユーザーIDを生成する
      parameters:
        - name: ttl
          in: query
          description: ユーザーIDの有効期限(秒)。デフォルトは86400秒(1日)
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: '01GR6FXNBHTQSAF7CZBVNP48NX'
        '500':
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /exist_user_id:
    post:
      tags:
        - id
      summary: ユーザーIDが存在するかチェックする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: 'user ID exists'
        '400':
          description: 不正なユーザーID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /create_room:
    post:
      tags:
        - room
      summary: 新しい部屋を作成する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: {"room id": '123456'}
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /join_room:
    post:
      tags:
        - room
      summary: 既存の部屋に参加する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
      parameters:
        - name: room_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: 'successfully joined the room'
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 部屋が見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /get_room_users:
    get:
      tags:
        - room
      summary: 部屋に参加しているユーザー一覧を取得する
      parameters:
        - name: room_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomInfo'
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /change_game_master:
    put:
      tags:
        - room
      summary: ゲームマスターを変更する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
      parameters:
        - name: room_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: '新しいゲームマスターのユーザーID'
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 部屋がみつからないまたはユーザーが部屋に存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /ping:
    get:
      tags:
        - debug
      summary: ヘルスチェック
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: 'pong'
components:
  schemas:
    UserInfo:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        lang:
          type: string
      required:
        - id
        - name
        - lang
    Error:
      type: object
      properties:
        message:
          type: string
    RoomInfo:
      type: object
      properties:
        game_master_id:
          type: string
        total_players:
          type: integer
        game_rounds:
          type: integer
        users:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/UserInfo'
