openapi: 3.0.3
info:
  title: Scene Hunter API
  description: 'Scene HunterのAPI定義書 エラーはすべて {"message": "err"} で返す'
  version: 0.1.0
servers:
  - url: http://localhost:8080/api
    description: ローカル開発環境
  - url: https://sh.yashikota.com/api
    description: 本番環境
tags:
  - name: id
    description: ユーザーIDに関するAPI
  - name: room
    description: 部屋に関するAPI
  - name: debug
    description: デバッグ用API
paths:
  /generate_user_id:
    get:
      tags:
        - id
      summary: ユーザーIDを生成する
      parameters:
        - name: TTL
          in: query
          description: ユーザーIDの有効期限(秒)。デフォルトは86400秒(1日)
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: {"user_id": "01GR6FXNBHTQSAF7CZBVNP48NX"}
        "500":
          description: ユーザーIDの生成に失敗 もしくは ユーザーIDのTTLの設定に失敗
  /exist_user_id:
    post:
      tags:
        - id
      summary: ユーザーIDが存在するかチェックする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: {"message": "user id exists"}
        "500":
          description: 不正なユーザーIDを指定 もしくは ユーザーIDのTTLの取得に失敗
  /create_room:
    post:
      tags:
        - room
      summary: 新しい部屋を作成する。
      description: リクエストしてきたユーザーのIDとナノ秒のUNIXタイムスタンプを結合後ハッシュ化して、N桁のRoomIDを生成。RoomIDが衝突していないことを確認後、部屋を作成しリクエストしてきたユーザーをGameMasterとして参加させる。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInfo"
      responses:
        "201":
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: {"room_id": "123456"}
        "400":
          description: 不正なリクエスト
        "500":
          description: 内部サーバーエラー
  /join_room:
    post:
      tags:
        - room
      summary: 既存の部屋に参加する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInfo"
      parameters:
        - name: room_id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: {"message": "successfully joined the room"}
        "400":
          description: 不正なリクエスト
        "404":
          description: 部屋が見つからない
        "500":
          description: 内部サーバーエラー
  /get_room_users:
    get:
      tags:
        - room
      summary: 部屋に参加しているユーザー一覧を取得する
      parameters:
        - name: room_id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                example: {
                  "users": [{
                    "game_master_id": "01J0HJQ97M468YGVJNTTPMAZ2W",
                    "total_players": 0,
                    "game_rounds": 3,
                    "users": {
                      "01J0HJQ97M468YGVJNTTPMAZ2W": {
                        "id": "01J0HJQ97M468YGVJNTTPMAZ2W",
                        "name": "hoge",
                        "lang": "ja",
                        "status": "active",
                        "photo_score_index": 4,
                        "score": {
                          "0": 43.8428,
                          "1": 44.8822,
                          "2": 25.4512,
                          "3": 35.2122
                        },
                        "photo": {
                          "0": "uploads/286193/01J0HMRXE70000000000000000.jpeg",
                          "1": "uploads/286193/01J0HMRZRT0000000000000000.jpeg",
                          "2": "uploads/286193/01J0HMSB7Z0000000000000000.jpeg",
                          "3": "uploads/286193/01J0HMSEC10000000000000000.jpeg"
                        }
                      }
                    }
                  }
                ]}
        "400":
          description: 不正なリクエスト
        "500":
          description: 内部サーバーエラー
  /change_game_master:
    put:
      tags:
        - room
      summary: ゲームマスターを変更する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInfo"
      parameters:
        - name: room_id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: {"user_id": "01GR6FXNBHTQSAF7CZBVNP48NX"}
        "400":
          description: 不正なリクエスト
        "404":
          description: 部屋がみつからないまたはユーザーが部屋に存在しない
        "500":
          description: 内部サーバーエラー
  /ping:
    get:
      tags:
        - debug
      summary: ヘルスチェック
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: string
                example: "pong"
components:
  schemas:
    UserInfo:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        lang:
          type: string
      required:
        - id
        - name
        - lang
    Error:
      type: object
      properties:
        message:
          type: string
    RoomInfo:
      type: object
      properties:
        game_master_id:
          type: string
        total_players:
          type: integer
        game_rounds:
          type: integer
        users:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/UserInfo'
